/**
 * @file model_car_net.h
 *
 * @brief This header file was generated by cantools version 41.4.3 Thu Jun 18 15:46:39 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef MODEL_CAR_NET_H
#define MODEL_CAR_NET_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define MODEL_CAR_NET_HEARTBEAT_FRAME_ID (0x50u)
#define MODEL_CAR_NET_DRIVE_CMD_FRAME_ID (0x100u)
#define MODEL_CAR_NET_DRIVER_SEAT_CMD_FRAME_ID (0x110u)
#define MODEL_CAR_NET_PASSENGER_SEAT_CMD_FRAME_ID (0x111u)
#define MODEL_CAR_NET_REAR_LEFT_SEAT_CMD_FRAME_ID (0x120u)
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_FRAME_ID (0x121u)
#define MODEL_CAR_NET_DRIVE_STATUS_FRAME_ID (0x200u)
#define MODEL_CAR_NET_DRIVER_SEAT_STATUS_FRAME_ID (0x210u)
#define MODEL_CAR_NET_PASSENGER_SEAT_STATUS_FRAME_ID (0x211u)
#define MODEL_CAR_NET_REAR_LEFT_SEAT_STATUS_FRAME_ID (0x220u)
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_STATUS_FRAME_ID (0x221u)
#define MODEL_CAR_NET_HMI_EMERGENCY_FRAME_ID (0x10u)

/* Frame lengths in bytes. */
#define MODEL_CAR_NET_HEARTBEAT_LENGTH (1u)
#define MODEL_CAR_NET_DRIVE_CMD_LENGTH (8u)
#define MODEL_CAR_NET_DRIVER_SEAT_CMD_LENGTH (2u)
#define MODEL_CAR_NET_PASSENGER_SEAT_CMD_LENGTH (2u)
#define MODEL_CAR_NET_REAR_LEFT_SEAT_CMD_LENGTH (2u)
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_LENGTH (3u)
#define MODEL_CAR_NET_DRIVE_STATUS_LENGTH (8u)
#define MODEL_CAR_NET_DRIVER_SEAT_STATUS_LENGTH (2u)
#define MODEL_CAR_NET_PASSENGER_SEAT_STATUS_LENGTH (2u)
#define MODEL_CAR_NET_REAR_LEFT_SEAT_STATUS_LENGTH (2u)
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_STATUS_LENGTH (2u)
#define MODEL_CAR_NET_HMI_EMERGENCY_LENGTH (1u)

/* Extended or standard frame types. */
#define MODEL_CAR_NET_HEARTBEAT_IS_EXTENDED (0)
#define MODEL_CAR_NET_DRIVE_CMD_IS_EXTENDED (0)
#define MODEL_CAR_NET_DRIVER_SEAT_CMD_IS_EXTENDED (0)
#define MODEL_CAR_NET_PASSENGER_SEAT_CMD_IS_EXTENDED (0)
#define MODEL_CAR_NET_REAR_LEFT_SEAT_CMD_IS_EXTENDED (0)
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_IS_EXTENDED (0)
#define MODEL_CAR_NET_DRIVE_STATUS_IS_EXTENDED (0)
#define MODEL_CAR_NET_DRIVER_SEAT_STATUS_IS_EXTENDED (0)
#define MODEL_CAR_NET_PASSENGER_SEAT_STATUS_IS_EXTENDED (0)
#define MODEL_CAR_NET_REAR_LEFT_SEAT_STATUS_IS_EXTENDED (0)
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_STATUS_IS_EXTENDED (0)
#define MODEL_CAR_NET_HMI_EMERGENCY_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define MODEL_CAR_NET_HEARTBEAT_NAME "Heartbeat"
#define MODEL_CAR_NET_DRIVE_CMD_NAME "Drive_Cmd"
#define MODEL_CAR_NET_DRIVER_SEAT_CMD_NAME "Driver_Seat_Cmd"
#define MODEL_CAR_NET_PASSENGER_SEAT_CMD_NAME "Passenger_Seat_Cmd"
#define MODEL_CAR_NET_REAR_LEFT_SEAT_CMD_NAME "Rear_Left_Seat_Cmd"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_NAME "Rear_Right_Seat_Cmd"
#define MODEL_CAR_NET_DRIVE_STATUS_NAME "Drive_Status"
#define MODEL_CAR_NET_DRIVER_SEAT_STATUS_NAME "Driver_Seat_Status"
#define MODEL_CAR_NET_PASSENGER_SEAT_STATUS_NAME "Passenger_Seat_Status"
#define MODEL_CAR_NET_REAR_LEFT_SEAT_STATUS_NAME "Rear_Left_Seat_Status"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_STATUS_NAME "Rear_Right_Seat_Status"
#define MODEL_CAR_NET_HMI_EMERGENCY_NAME "HMI_Emergency"

/* Signal Names. */
#define MODEL_CAR_NET_HEARTBEAT_ALIVE_COUNTER_NAME "Alive_Counter"
#define MODEL_CAR_NET_DRIVE_CMD_TARGET_VELOCITY_NAME "Target_Velocity"
#define MODEL_CAR_NET_DRIVE_CMD_STEERING_ANGLE_NAME "Steering_Angle"
#define MODEL_CAR_NET_DRIVE_CMD_BRAKE_DEPTH_NAME "Brake_Depth"
#define MODEL_CAR_NET_DRIVE_CMD_GEAR_STATUS_NAME "Gear_Status"
#define MODEL_CAR_NET_DRIVER_SEAT_CMD_DRV_RECLINE_ANGLE_NAME "Drv_Recline_Angle"
#define MODEL_CAR_NET_DRIVER_SEAT_CMD_DRV_ROTATION_ANGLE_NAME "Drv_Rotation_Angle"
#define MODEL_CAR_NET_PASSENGER_SEAT_CMD_PSGR_RECLINE_ANGLE_NAME "Psgr_Recline_Angle"
#define MODEL_CAR_NET_PASSENGER_SEAT_CMD_PSGR_ROTATION_ANGLE_NAME "Psgr_Rotation_Angle"
#define MODEL_CAR_NET_REAR_LEFT_SEAT_CMD_RL_RECLINE_ANGLE_NAME "RL_Recline_Angle"
#define MODEL_CAR_NET_REAR_LEFT_SEAT_CMD_RL_SLIDE_POSITION_NAME "RL_Slide_Position"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_RR_RECLINE_ANGLE_NAME "RR_Recline_Angle"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_RR_SLIDE_POSITION_NAME "RR_Slide_Position"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_CMD_CARGO_LAMP_STATUS_NAME "Cargo_Lamp_Status"
#define MODEL_CAR_NET_DRIVE_STATUS_CURRENT_VELOCITY_NAME "Current_Velocity"
#define MODEL_CAR_NET_DRIVE_STATUS_DRIVE_MOTOR_CURRENT_NAME "Drive_Motor_Current"
#define MODEL_CAR_NET_DRIVE_STATUS_CURRENT_GEAR_STATUS_NAME "Current_Gear_Status"
#define MODEL_CAR_NET_DRIVER_SEAT_STATUS_CURR_DRV_RECLINE_NAME "Curr_Drv_Recline"
#define MODEL_CAR_NET_DRIVER_SEAT_STATUS_DRV_PINCH_DETECTED_NAME "Drv_Pinch_Detected"
#define MODEL_CAR_NET_PASSENGER_SEAT_STATUS_CURR_PSGR_RECLINE_NAME "Curr_Psgr_Recline"
#define MODEL_CAR_NET_PASSENGER_SEAT_STATUS_PSGR_PINCH_DETECTED_NAME "Psgr_Pinch_Detected"
#define MODEL_CAR_NET_REAR_LEFT_SEAT_STATUS_CURR_RL_RECLINE_NAME "Curr_RL_Recline"
#define MODEL_CAR_NET_REAR_LEFT_SEAT_STATUS_RL_PINCH_DETECTED_NAME "RL_Pinch_Detected"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_STATUS_CURR_RR_RECLINE_NAME "Curr_RR_Recline"
#define MODEL_CAR_NET_REAR_RIGHT_SEAT_STATUS_RR_PINCH_DETECTED_NAME "RR_Pinch_Detected"
#define MODEL_CAR_NET_HMI_EMERGENCY_EMERGENCY_STOP_FLAG_NAME "Emergency_Stop_Flag"

/**
 * Signals in message Heartbeat.
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_heartbeat_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t alive_counter;
};

/**
 * Signals in message Drive_Cmd.
 *
 * Powertrain command sent periodically from Supervisor
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_drive_cmd_t {
    /**
     * Range: 0..3000 (0..300 RPM)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t target_velocity;

    /**
     * Range: -135..135 (-135..135 Degree)
     * Scale: 1
     * Offset: 0
     */
    int8_t steering_angle;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_depth;

    /**
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gear_status;
};

/**
 * Signals in message Driver_Seat_Cmd.
 *
 * Driver power seat command from Supervisor
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_driver_seat_cmd_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t drv_recline_angle;

    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t drv_rotation_angle;
};

/**
 * Signals in message Passenger_Seat_Cmd.
 *
 * Passenger power seat command from Supervisor
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_passenger_seat_cmd_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t psgr_recline_angle;

    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t psgr_rotation_angle;
};

/**
 * Signals in message Rear_Left_Seat_Cmd.
 *
 * Rear Left power seat command from Supervisor
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_rear_left_seat_cmd_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rl_recline_angle;

    /**
     * Range: 0..100 (0..100 mm)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rl_slide_position;
};

/**
 * Signals in message Rear_Right_Seat_Cmd.
 *
 * Rear Right power seat command from Supervisor
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_rear_right_seat_cmd_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rr_recline_angle;

    /**
     * Range: 0..100 (0..100 mm)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rr_slide_position;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cargo_lamp_status;
};

/**
 * Signals in message Drive_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_drive_status_t {
    /**
     * Range: 0..3000 (0..300 RPM)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t current_velocity;

    /**
     * Range: 0..5000 (0..5000 mA)
     * Scale: 1
     * Offset: 0
     */
    uint16_t drive_motor_current;

    /**
     * Range: 0..2 (0..2 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t current_gear_status;
};

/**
 * Signals in message Driver_Seat_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_driver_seat_status_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t curr_drv_recline;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t drv_pinch_detected;
};

/**
 * Signals in message Passenger_Seat_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_passenger_seat_status_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t curr_psgr_recline;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t psgr_pinch_detected;
};

/**
 * Signals in message Rear_Left_Seat_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_rear_left_seat_status_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t curr_rl_recline;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rl_pinch_detected;
};

/**
 * Signals in message Rear_Right_Seat_Status.
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_rear_right_seat_status_t {
    /**
     * Range: 0..180 (0..180 Degree)
     * Scale: 1
     * Offset: 0
     */
    uint8_t curr_rr_recline;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rr_pinch_detected;
};

/**
 * Signals in message HMI_Emergency.
 *
 * Critical emergency stop signal triggered by HMI
 *
 * All signal values are as on the CAN bus.
 */
struct model_car_net_hmi_emergency_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t emergency_stop_flag;
};

/**
 * Pack message Heartbeat.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_heartbeat_pack(
    uint8_t *dst_p,
    const struct model_car_net_heartbeat_t *src_p,
    size_t size);

/**
 * Unpack message Heartbeat.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_heartbeat_unpack(
    struct model_car_net_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Heartbeat.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_heartbeat_init(struct model_car_net_heartbeat_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_heartbeat_alive_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_heartbeat_alive_counter_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_heartbeat_alive_counter_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_heartbeat_alive_counter_is_in_phys_range(double value);

/**
 * Pack message Drive_Cmd.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_drive_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_drive_cmd_t *src_p,
    size_t size);

/**
 * Unpack message Drive_Cmd.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_drive_cmd_unpack(
    struct model_car_net_drive_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Drive_Cmd.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_drive_cmd_init(struct model_car_net_drive_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t model_car_net_drive_cmd_target_velocity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_cmd_target_velocity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_target_velocity_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_target_velocity_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t model_car_net_drive_cmd_steering_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_cmd_steering_angle_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_steering_angle_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_steering_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_drive_cmd_brake_depth_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_cmd_brake_depth_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_brake_depth_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_brake_depth_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_drive_cmd_gear_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_cmd_gear_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_gear_status_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_cmd_gear_status_is_in_phys_range(double value);

/**
 * Pack message Driver_Seat_Cmd.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_driver_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_driver_seat_cmd_t *src_p,
    size_t size);

/**
 * Unpack message Driver_Seat_Cmd.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_driver_seat_cmd_unpack(
    struct model_car_net_driver_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Driver_Seat_Cmd.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_driver_seat_cmd_init(struct model_car_net_driver_seat_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_driver_seat_cmd_drv_recline_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_driver_seat_cmd_drv_recline_angle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_cmd_drv_recline_angle_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_cmd_drv_recline_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_driver_seat_cmd_drv_rotation_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_driver_seat_cmd_drv_rotation_angle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_cmd_drv_rotation_angle_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_cmd_drv_rotation_angle_is_in_phys_range(double value);

/**
 * Pack message Passenger_Seat_Cmd.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_passenger_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_passenger_seat_cmd_t *src_p,
    size_t size);

/**
 * Unpack message Passenger_Seat_Cmd.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_passenger_seat_cmd_unpack(
    struct model_car_net_passenger_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Passenger_Seat_Cmd.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_passenger_seat_cmd_init(struct model_car_net_passenger_seat_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_passenger_seat_cmd_psgr_recline_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_passenger_seat_cmd_psgr_recline_angle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_cmd_psgr_recline_angle_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_cmd_psgr_recline_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_passenger_seat_cmd_psgr_rotation_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_passenger_seat_cmd_psgr_rotation_angle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_cmd_psgr_rotation_angle_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_cmd_psgr_rotation_angle_is_in_phys_range(double value);

/**
 * Pack message Rear_Left_Seat_Cmd.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_rear_left_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_left_seat_cmd_t *src_p,
    size_t size);

/**
 * Unpack message Rear_Left_Seat_Cmd.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_rear_left_seat_cmd_unpack(
    struct model_car_net_rear_left_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Rear_Left_Seat_Cmd.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_rear_left_seat_cmd_init(struct model_car_net_rear_left_seat_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_left_seat_cmd_rl_recline_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_left_seat_cmd_rl_recline_angle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_cmd_rl_recline_angle_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_cmd_rl_recline_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_left_seat_cmd_rl_slide_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_left_seat_cmd_rl_slide_position_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_cmd_rl_slide_position_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_cmd_rl_slide_position_is_in_phys_range(double value);

/**
 * Pack message Rear_Right_Seat_Cmd.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_rear_right_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_right_seat_cmd_t *src_p,
    size_t size);

/**
 * Unpack message Rear_Right_Seat_Cmd.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_rear_right_seat_cmd_unpack(
    struct model_car_net_rear_right_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Rear_Right_Seat_Cmd.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_rear_right_seat_cmd_init(struct model_car_net_rear_right_seat_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_right_seat_cmd_rr_recline_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_right_seat_cmd_rr_recline_angle_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_cmd_rr_recline_angle_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_cmd_rr_recline_angle_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_right_seat_cmd_rr_slide_position_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_right_seat_cmd_rr_slide_position_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_cmd_rr_slide_position_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_cmd_rr_slide_position_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_right_seat_cmd_cargo_lamp_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_right_seat_cmd_cargo_lamp_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_cmd_cargo_lamp_status_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_cmd_cargo_lamp_status_is_in_phys_range(double value);

/**
 * Pack message Drive_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_drive_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_drive_status_t *src_p,
    size_t size);

/**
 * Unpack message Drive_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_drive_status_unpack(
    struct model_car_net_drive_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Drive_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_drive_status_init(struct model_car_net_drive_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t model_car_net_drive_status_current_velocity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_status_current_velocity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_status_current_velocity_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_status_current_velocity_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t model_car_net_drive_status_drive_motor_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_status_drive_motor_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_status_drive_motor_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_status_drive_motor_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_drive_status_current_gear_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_drive_status_current_gear_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_status_current_gear_status_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_drive_status_current_gear_status_is_in_phys_range(double value);

/**
 * Pack message Driver_Seat_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_driver_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_driver_seat_status_t *src_p,
    size_t size);

/**
 * Unpack message Driver_Seat_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_driver_seat_status_unpack(
    struct model_car_net_driver_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Driver_Seat_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_driver_seat_status_init(struct model_car_net_driver_seat_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_driver_seat_status_curr_drv_recline_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_driver_seat_status_curr_drv_recline_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_status_curr_drv_recline_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_status_curr_drv_recline_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_driver_seat_status_drv_pinch_detected_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_driver_seat_status_drv_pinch_detected_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_status_drv_pinch_detected_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_driver_seat_status_drv_pinch_detected_is_in_phys_range(double value);

/**
 * Pack message Passenger_Seat_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_passenger_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_passenger_seat_status_t *src_p,
    size_t size);

/**
 * Unpack message Passenger_Seat_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_passenger_seat_status_unpack(
    struct model_car_net_passenger_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Passenger_Seat_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_passenger_seat_status_init(struct model_car_net_passenger_seat_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_passenger_seat_status_curr_psgr_recline_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_passenger_seat_status_curr_psgr_recline_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_status_curr_psgr_recline_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_status_curr_psgr_recline_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_passenger_seat_status_psgr_pinch_detected_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_passenger_seat_status_psgr_pinch_detected_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_status_psgr_pinch_detected_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_passenger_seat_status_psgr_pinch_detected_is_in_phys_range(double value);

/**
 * Pack message Rear_Left_Seat_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_rear_left_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_left_seat_status_t *src_p,
    size_t size);

/**
 * Unpack message Rear_Left_Seat_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_rear_left_seat_status_unpack(
    struct model_car_net_rear_left_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Rear_Left_Seat_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_rear_left_seat_status_init(struct model_car_net_rear_left_seat_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_left_seat_status_curr_rl_recline_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_left_seat_status_curr_rl_recline_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_status_curr_rl_recline_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_status_curr_rl_recline_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_left_seat_status_rl_pinch_detected_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_left_seat_status_rl_pinch_detected_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_status_rl_pinch_detected_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_left_seat_status_rl_pinch_detected_is_in_phys_range(double value);

/**
 * Pack message Rear_Right_Seat_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_rear_right_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_right_seat_status_t *src_p,
    size_t size);

/**
 * Unpack message Rear_Right_Seat_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_rear_right_seat_status_unpack(
    struct model_car_net_rear_right_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Rear_Right_Seat_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_rear_right_seat_status_init(struct model_car_net_rear_right_seat_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_right_seat_status_curr_rr_recline_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_right_seat_status_curr_rr_recline_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_status_curr_rr_recline_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_status_curr_rr_recline_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_rear_right_seat_status_rr_pinch_detected_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_rear_right_seat_status_rr_pinch_detected_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_status_rr_pinch_detected_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_rear_right_seat_status_rr_pinch_detected_is_in_phys_range(double value);

/**
 * Pack message HMI_Emergency.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int model_car_net_hmi_emergency_pack(
    uint8_t *dst_p,
    const struct model_car_net_hmi_emergency_t *src_p,
    size_t size);

/**
 * Unpack message HMI_Emergency.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int model_car_net_hmi_emergency_unpack(
    struct model_car_net_hmi_emergency_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HMI_Emergency.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int model_car_net_hmi_emergency_init(struct model_car_net_hmi_emergency_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t model_car_net_hmi_emergency_emergency_stop_flag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double model_car_net_hmi_emergency_emergency_stop_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_hmi_emergency_emergency_stop_flag_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool model_car_net_hmi_emergency_emergency_stop_flag_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
