/**
 * @file model_car_net.c
 *
 * @brief This source file was generated by cantools version 41.4.3 Thu Jun 18 15:46:39 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "model_car_net.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int model_car_net_heartbeat_pack(
    uint8_t *dst_p,
    const struct model_car_net_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->alive_counter, 0u, 0xffu);

    return (1);
}

int model_car_net_heartbeat_unpack(
    struct model_car_net_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->alive_counter = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int model_car_net_heartbeat_init(struct model_car_net_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_heartbeat_t));

    return 0;
}

uint8_t model_car_net_heartbeat_alive_counter_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_heartbeat_alive_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_heartbeat_alive_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool model_car_net_heartbeat_alive_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int model_car_net_drive_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_drive_cmd_t *src_p,
    size_t size)
{
    uint8_t steering_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->target_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->target_velocity, 8u, 0xffu);
    steering_angle = (uint8_t)src_p->steering_angle;
    dst_p[2] |= pack_left_shift_u8(steering_angle, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_depth, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->gear_status, 0u, 0x03u);

    return (8);
}

int model_car_net_drive_cmd_unpack(
    struct model_car_net_drive_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t steering_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_velocity = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->target_velocity |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    steering_angle = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->steering_angle = (int8_t)steering_angle;
    dst_p->brake_depth = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->gear_status = unpack_right_shift_u8(src_p[4], 0u, 0x03u);

    return (0);
}

int model_car_net_drive_cmd_init(struct model_car_net_drive_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_drive_cmd_t));

    return 0;
}

uint16_t model_car_net_drive_cmd_target_velocity_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double model_car_net_drive_cmd_target_velocity_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool model_car_net_drive_cmd_target_velocity_is_in_range(uint16_t value)
{
    return (value <= 3000u);
}

bool model_car_net_drive_cmd_target_velocity_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 300.0));
}

int8_t model_car_net_drive_cmd_steering_angle_encode(double value)
{
    return (int8_t)(value);
}

double model_car_net_drive_cmd_steering_angle_decode(int8_t value)
{
    return ((double)value);
}

bool model_car_net_drive_cmd_steering_angle_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

bool model_car_net_drive_cmd_steering_angle_is_in_phys_range(double value)
{
    return ((value >= -135.0) && (value <= 135.0));
}

uint8_t model_car_net_drive_cmd_brake_depth_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_drive_cmd_brake_depth_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_drive_cmd_brake_depth_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool model_car_net_drive_cmd_brake_depth_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

uint8_t model_car_net_drive_cmd_gear_status_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_drive_cmd_gear_status_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_drive_cmd_gear_status_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool model_car_net_drive_cmd_gear_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

int model_car_net_driver_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_driver_seat_cmd_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->drv_recline_angle, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->drv_rotation_angle, 0u, 0xffu);

    return (2);
}

int model_car_net_driver_seat_cmd_unpack(
    struct model_car_net_driver_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->drv_recline_angle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->drv_rotation_angle = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int model_car_net_driver_seat_cmd_init(struct model_car_net_driver_seat_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_driver_seat_cmd_t));

    return 0;
}

uint8_t model_car_net_driver_seat_cmd_drv_recline_angle_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_driver_seat_cmd_drv_recline_angle_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_driver_seat_cmd_drv_recline_angle_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_driver_seat_cmd_drv_recline_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_driver_seat_cmd_drv_rotation_angle_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_driver_seat_cmd_drv_rotation_angle_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_driver_seat_cmd_drv_rotation_angle_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_driver_seat_cmd_drv_rotation_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

int model_car_net_passenger_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_passenger_seat_cmd_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->psgr_recline_angle, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->psgr_rotation_angle, 0u, 0xffu);

    return (2);
}

int model_car_net_passenger_seat_cmd_unpack(
    struct model_car_net_passenger_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->psgr_recline_angle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->psgr_rotation_angle = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int model_car_net_passenger_seat_cmd_init(struct model_car_net_passenger_seat_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_passenger_seat_cmd_t));

    return 0;
}

uint8_t model_car_net_passenger_seat_cmd_psgr_recline_angle_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_passenger_seat_cmd_psgr_recline_angle_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_passenger_seat_cmd_psgr_recline_angle_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_passenger_seat_cmd_psgr_recline_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_passenger_seat_cmd_psgr_rotation_angle_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_passenger_seat_cmd_psgr_rotation_angle_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_passenger_seat_cmd_psgr_rotation_angle_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_passenger_seat_cmd_psgr_rotation_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

int model_car_net_rear_left_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_left_seat_cmd_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->rl_recline_angle, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_slide_position, 0u, 0xffu);

    return (2);
}

int model_car_net_rear_left_seat_cmd_unpack(
    struct model_car_net_rear_left_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->rl_recline_angle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rl_slide_position = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int model_car_net_rear_left_seat_cmd_init(struct model_car_net_rear_left_seat_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_rear_left_seat_cmd_t));

    return 0;
}

uint8_t model_car_net_rear_left_seat_cmd_rl_recline_angle_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_left_seat_cmd_rl_recline_angle_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_left_seat_cmd_rl_recline_angle_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_rear_left_seat_cmd_rl_recline_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_rear_left_seat_cmd_rl_slide_position_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_left_seat_cmd_rl_slide_position_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_left_seat_cmd_rl_slide_position_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool model_car_net_rear_left_seat_cmd_rl_slide_position_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

int model_car_net_rear_right_seat_cmd_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_right_seat_cmd_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->rr_recline_angle, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_slide_position, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->cargo_lamp_status, 0u, 0x01u);

    return (3);
}

int model_car_net_rear_right_seat_cmd_unpack(
    struct model_car_net_rear_right_seat_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->rr_recline_angle = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rr_slide_position = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->cargo_lamp_status = unpack_right_shift_u8(src_p[2], 0u, 0x01u);

    return (0);
}

int model_car_net_rear_right_seat_cmd_init(struct model_car_net_rear_right_seat_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_rear_right_seat_cmd_t));

    return 0;
}

uint8_t model_car_net_rear_right_seat_cmd_rr_recline_angle_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_right_seat_cmd_rr_recline_angle_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_right_seat_cmd_rr_recline_angle_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_rear_right_seat_cmd_rr_recline_angle_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_rear_right_seat_cmd_rr_slide_position_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_right_seat_cmd_rr_slide_position_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_right_seat_cmd_rr_slide_position_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool model_car_net_rear_right_seat_cmd_rr_slide_position_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

uint8_t model_car_net_rear_right_seat_cmd_cargo_lamp_status_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_right_seat_cmd_cargo_lamp_status_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_right_seat_cmd_cargo_lamp_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool model_car_net_rear_right_seat_cmd_cargo_lamp_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int model_car_net_drive_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_drive_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->current_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->current_velocity, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->drive_motor_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->drive_motor_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->current_gear_status, 0u, 0x03u);

    return (8);
}

int model_car_net_drive_status_unpack(
    struct model_car_net_drive_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->current_velocity = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->current_velocity |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->drive_motor_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->drive_motor_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_gear_status = unpack_right_shift_u8(src_p[4], 0u, 0x03u);

    return (0);
}

int model_car_net_drive_status_init(struct model_car_net_drive_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_drive_status_t));

    return 0;
}

uint16_t model_car_net_drive_status_current_velocity_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double model_car_net_drive_status_current_velocity_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool model_car_net_drive_status_current_velocity_is_in_range(uint16_t value)
{
    return (value <= 3000u);
}

bool model_car_net_drive_status_current_velocity_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 300.0));
}

uint16_t model_car_net_drive_status_drive_motor_current_encode(double value)
{
    return (uint16_t)(value);
}

double model_car_net_drive_status_drive_motor_current_decode(uint16_t value)
{
    return ((double)value);
}

bool model_car_net_drive_status_drive_motor_current_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool model_car_net_drive_status_drive_motor_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 5000.0));
}

uint8_t model_car_net_drive_status_current_gear_status_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_drive_status_current_gear_status_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_drive_status_current_gear_status_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool model_car_net_drive_status_current_gear_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 2.0));
}

int model_car_net_driver_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_driver_seat_status_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->curr_drv_recline, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->drv_pinch_detected, 0u, 0x01u);

    return (2);
}

int model_car_net_driver_seat_status_unpack(
    struct model_car_net_driver_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->curr_drv_recline = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->drv_pinch_detected = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    return (0);
}

int model_car_net_driver_seat_status_init(struct model_car_net_driver_seat_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_driver_seat_status_t));

    return 0;
}

uint8_t model_car_net_driver_seat_status_curr_drv_recline_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_driver_seat_status_curr_drv_recline_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_driver_seat_status_curr_drv_recline_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_driver_seat_status_curr_drv_recline_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_driver_seat_status_drv_pinch_detected_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_driver_seat_status_drv_pinch_detected_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_driver_seat_status_drv_pinch_detected_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool model_car_net_driver_seat_status_drv_pinch_detected_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int model_car_net_passenger_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_passenger_seat_status_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->curr_psgr_recline, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->psgr_pinch_detected, 0u, 0x01u);

    return (2);
}

int model_car_net_passenger_seat_status_unpack(
    struct model_car_net_passenger_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->curr_psgr_recline = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->psgr_pinch_detected = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    return (0);
}

int model_car_net_passenger_seat_status_init(struct model_car_net_passenger_seat_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_passenger_seat_status_t));

    return 0;
}

uint8_t model_car_net_passenger_seat_status_curr_psgr_recline_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_passenger_seat_status_curr_psgr_recline_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_passenger_seat_status_curr_psgr_recline_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_passenger_seat_status_curr_psgr_recline_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_passenger_seat_status_psgr_pinch_detected_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_passenger_seat_status_psgr_pinch_detected_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_passenger_seat_status_psgr_pinch_detected_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool model_car_net_passenger_seat_status_psgr_pinch_detected_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int model_car_net_rear_left_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_left_seat_status_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->curr_rl_recline, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_pinch_detected, 0u, 0x01u);

    return (2);
}

int model_car_net_rear_left_seat_status_unpack(
    struct model_car_net_rear_left_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->curr_rl_recline = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rl_pinch_detected = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    return (0);
}

int model_car_net_rear_left_seat_status_init(struct model_car_net_rear_left_seat_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_rear_left_seat_status_t));

    return 0;
}

uint8_t model_car_net_rear_left_seat_status_curr_rl_recline_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_left_seat_status_curr_rl_recline_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_left_seat_status_curr_rl_recline_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_rear_left_seat_status_curr_rl_recline_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_rear_left_seat_status_rl_pinch_detected_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_left_seat_status_rl_pinch_detected_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_left_seat_status_rl_pinch_detected_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool model_car_net_rear_left_seat_status_rl_pinch_detected_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int model_car_net_rear_right_seat_status_pack(
    uint8_t *dst_p,
    const struct model_car_net_rear_right_seat_status_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->curr_rr_recline, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_pinch_detected, 0u, 0x01u);

    return (2);
}

int model_car_net_rear_right_seat_status_unpack(
    struct model_car_net_rear_right_seat_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->curr_rr_recline = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rr_pinch_detected = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    return (0);
}

int model_car_net_rear_right_seat_status_init(struct model_car_net_rear_right_seat_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_rear_right_seat_status_t));

    return 0;
}

uint8_t model_car_net_rear_right_seat_status_curr_rr_recline_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_right_seat_status_curr_rr_recline_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_right_seat_status_curr_rr_recline_is_in_range(uint8_t value)
{
    return (value <= 180u);
}

bool model_car_net_rear_right_seat_status_curr_rr_recline_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 180.0));
}

uint8_t model_car_net_rear_right_seat_status_rr_pinch_detected_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_rear_right_seat_status_rr_pinch_detected_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_rear_right_seat_status_rr_pinch_detected_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool model_car_net_rear_right_seat_status_rr_pinch_detected_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int model_car_net_hmi_emergency_pack(
    uint8_t *dst_p,
    const struct model_car_net_hmi_emergency_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->emergency_stop_flag, 0u, 0x01u);

    return (1);
}

int model_car_net_hmi_emergency_unpack(
    struct model_car_net_hmi_emergency_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->emergency_stop_flag = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int model_car_net_hmi_emergency_init(struct model_car_net_hmi_emergency_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct model_car_net_hmi_emergency_t));

    return 0;
}

uint8_t model_car_net_hmi_emergency_emergency_stop_flag_encode(double value)
{
    return (uint8_t)(value);
}

double model_car_net_hmi_emergency_emergency_stop_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool model_car_net_hmi_emergency_emergency_stop_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool model_car_net_hmi_emergency_emergency_stop_flag_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}
